---
# ============================================================
# requirements.yml — Collections Ansible requises
# ============================================================
collections:
  - name: community.docker
    version: ">=5.0.0"
  - name: community.general
    version: ">=9.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
