---
# Inventaire Ansible - Serveur VPN & Vault
# Remplacer les valeurs par celles de votre serveur

all:
  hosts:
    vpn-vault-server:
      ansible_host: "{{ server_ip }}"
      ansible_port: "{{ ssh_port }}"
      ansible_user: "{{ deploy_user }}"
      ansible_ssh_private_key_file: "{{ ssh_private_key_path }}"
